M48
; DRILL file {KiCad (6.0.8)} date Wed Nov 30 15:49:36 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-30T15:49:36-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X27.03Y-34.075
X27.03Y-38.925
T2
X24.0Y-33.775
X24.0Y-39.225
T3
X20.0Y-23.5
X20.0Y-52.0
X189.0Y-23.5
X189.0Y-52.0
T0
M30
